"""User added authentication

Revision ID: 27fdb5788761
Revises: 06e690a18d24
Create Date: 2016-08-31 14:25:26.815623

"""

# revision identifiers, used by Alembic.
revision = '27fdb5788761'
down_revision = '06e690a18d24'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
